name: hetu_script_dev_tools
description: Extensions for Hetu Script dart package. Includes file system resource context helper class and command line REPL for Hetu Script.
version: 0.1.0+2
homepage: https://github.com/hetu-script/hetu-script
publish_to: none

executables:
  hetu: cli_tool

environment:
  sdk: ^3.0.0

dependencies:
  path: ^1.9.0
  args: ^2.5.0
  http: ^1.2.2
  pub_semver: ^2.1.4
  hetu_script:
    path: ../hetu_script

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
