name: hetu_script_flutter
description: Extension for Hetu Script. Makes it easier to use Hetu Script in Flutter apps.
version: 0.1.0+2
homepage: https://github.com/hetu-script/hetu-script
publish_to: none

environment:
  sdk: ^3.0.0
  flutter: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

  path: ^1.9.0
  hetu_script:
    path: ../hetu_script

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
